#############
# Variables #
# Front-end
export TEST_DB_HIVE_METASTORE=0.5

# Metabase
export TEST_DB_METABASE=0.6

# Auth
export TEST_DB_PUMPWOOD_AUTH=0.83
export PUMPWOOD_AUTH_APP=1.12
export PUMPWOOD_AUTH_STATIC=0.5
export PUMPWOOD_LOG_WORKER=1.3

# Datalake
export TEST_DB_PUMPWOOD_DATALAKE=1.14
export PUMPWOOD_DATALAKE_APP=1.11
export PUMPWOOD_DATALOADER_WORKER=1.3

# Description Matcher
export TEST_DB_PUMPWOOD_DESCRIPTION_MATCHER=0.10
export PUMPWOOD_DESCRIPTION_MATCHER_APP=1.5

# ETL
export TEST_DB_PUMPWOOD_ETL=0.42
export PUMPWOOD_ETL=1.3
export PUMPWOOD_ETL_WORKER=1.1

# Airflow
export TEST_DB_AIRFLOW=0.7
export AIRFLOW=0.22
